# OpenAI Secret
OPENAI_API_KEY = "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"

# Azure Blob Storage
[azure_blob]
connection_string = "DefaultEndpointsProtocol=https;AccountName=adlsgde;AccountKey=eV5gpHcACmV6oktkCgEnNOFIBVaA7y3xtRL83wLoqCzV4LdSwmlK+wkIFgCdJRzb2oligJwICMf2+AStp8TqOA==;EndpointSuffix=core.windows.net"
container_name = "mentee-responses"

[email]
sender = "chris.gambill@gambilldataengineering.com"
password = "dkhp yzqt pitq shsa"  # Use an app password if using Gmail
smtp_server = "smtp.gmail.com"
smtp_port = 587